### ISSUE TITLE
[redis-browser] Unable to connect to http://localhost:4567/

### ISSUE THREAD

**Issue by ismaail** [birkof/docker-images#2]
Starting **birkof/redis-browser** using docker-compose.yml works just fine, 

but the connection to `http://localhost:4567/` fails.

To solve this I have to add `--bind 0.0.0.0` to the **command** parameter.

---

docker-compose.yml file:

```yml
version: "2"

services:
  redis:
    container_name: redis_container
    image: redis:3.0

  redis-browser:
    container_name: redis_browser_container
    image: birkof/redis-browser
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "4567:4567"
    command: --url redis://redis:6379 --bind 0.0.0.0
```

- Docker version 17.05.0-ce
- docker-compose version 1.14.0, build unknown

And thank you for the Docker Image.
